services:
  - type: web
    name: wantokjobs
    runtime: node
    buildCommand: cd app && npm install && cd client && npm install && npx vite build
    startCommand: cd app && NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
